.github/workflows/cloud_deploy.yml
IdentityService, ApiGateway, dev directory and Blazor component addition
=> Resolving  (#1) -- adding the basic structure, project sut-up

.github/workflows/build_microservices.yml, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/appsettings.json, MiniSpace.Services.Identity/src/src.sln, MiniSpace.Services.Identity/tests/MiniSpace.Services.Identity.Application.UnitTests/MiniSpace.Services.Identity.Application.UnitTests.csproj, MiniSpace.Services.Identity/tests/MiniSpace.Services.Identity.Infrastructure.UnitTests/MiniSpace.Services.Identity.Infrastructure.UnitTests.csproj, MiniSpace.Web/src/MiniSpace.Web/Models/Identity/SignInModel.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Identity/SignUpModel.cs, MiniSpace.Web/src/MiniSpace.Web/Pages/SignIn.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/SignUp.razor, MiniSpace.Web/src/MiniSpace.Web/Properties/launchSettings.json, MiniSpace.Web/src/MiniSpace.Web/Shared/NavMenu.razor, MiniSpace.Web/src/MiniSpace.Web/Startup.cs, MiniSpace.Web/src/MiniSpace.Web/_Imports.razor, MiniSpace.Web/src/MiniSpace.Web/appsettings.json
Providingt the modification according to this issues
=> Setting up the database, modification the exisiting blazor component for the sign-in sign-up functionality, pipeline updates  (#2, #11, #12, #15)

MiniSpace.Web/src/MiniSpace.Web/appsettings.json
=> Modifying the blazor component settings  (#12)

.github/workflows/cloud_deploy.yml, MiniSpace/compose/services.yml
=> Deploy pipeline modification (#19)

MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada-async.yml, MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada.docker.yml, MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada.yml, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/appsettings.json, MiniSpace.Web/src/MiniSpace.Web/Areas/Identity/IdentityService.cs, MiniSpace.Web/src/MiniSpace.Web/DTO/JwtDto.cs, MiniSpace.Web/src/MiniSpace.Web/HttpClients/CustomHttpClient.cs, MiniSpace.Web/src/MiniSpace.Web/MiniSpace.Web.csproj, MiniSpace.Web/src/MiniSpace.Web/Pages/Greeting.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/SignIn.razor, MiniSpace.Web/src/MiniSpace.Web/appsettings.json
=> Merge with dev -- update the sign-in with respect to the blazor component  #19

MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/MiniSpace.Services.Identity.Api.csproj, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/appsettings.local.json, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Application/IIdentityContext.cs, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Application/MiniSpace.Services.Identity.Application.csproj, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Core/MiniSpace.Services.Identity.Core.csproj, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Infrastructure/Contexts/IdentityContext.cs, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Infrastructure/MiniSpace.Services.Identity.Infrastructure.csproj, MiniSpace.Services.Identity/tests/MiniSpace.Services.Identity.Infrastructure.UnitTests/MiniSpace.Services.Identity.Infrastructure.UnitTests.csproj, MiniSpace.Web/src/MiniSpace.Web/Areas/Identity/IIdentityService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Identity/IdentityService.cs, MiniSpace.Web/src/MiniSpace.Web/Pages/SignUp.razor, MiniSpace.Web/src/MiniSpace.Web/appsettings.Development.json
- Now services should be able to check if user has organizer permission or if they are banned
- Note that each service except IdentityService should have their IdentityContext.cs updated
=> Identity service update

.github/workflows/azure_synchronisation.yml
Pipeline udpate for the repo synchronisation with azure
https://stackoverflow.com/questions/55838359/using-git-repository-in-azure-devops-from-different-organization
=> (#40) update the synchronisation pipeline according to the udpated azure policies

MiniSpace.APIGateway/scripts/dockerize-tag-push.sh, MiniSpace.Services.Events/Dockerfile, MiniSpace.Services.Events/LICENSE, MiniSpace.Services.Events/scripts/dockerize-tag-push.sh, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Api/appsettings.docker.json, MiniSpace.Services.Identity/Dockerfile, MiniSpace.Services.Identity/scripts/dockerize-tag-push.sh, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/MiniSpace.Services.Identity.Api.sln, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/appsettings.json, MiniSpace.Services.Identity/src/MiniSpace.Services.Identity.Api/appsettings.local.json, MiniSpace.Services.Students/Dockerfile, MiniSpace.Services.Students/LICENSE, MiniSpace.Services.Students/scripts/dockerize-tag-push.sh, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Api/MiniSpace.Services.Students.Api.sln, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Api/appsettings.docker.json, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Api/appsettings.local.json, MiniSpace/compose/services.yml, MiniSpace/scripts/dockerize-all.sh
Merge with the dev branch -- resolve (#62)
=> (#62) test deploy for the services

MiniSpace.Services.Students/src/MiniSpace.Services.Students.Api/appsettings.local.json, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Application/Commands/Handlers/DeleteStudentHandler.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Application/Dto/StudentDto.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Application/Events/StudentCreated.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Application/Events/StudentDeleted.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Application/Events/StudentStateChanged.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Application/Events/StudentUpdated.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Application/IIdentityContext.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Core/Entities/Student.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Infrastructure/Contexts/IdentityContext.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Infrastructure/Mongo/Documents/Extensions.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Infrastructure/Mongo/Documents/StudentDocument.cs, MiniSpace.Services.Students/src/MiniSpace.Services.Students.Infrastructure/Services/EventMapper.cs
This changes are associated with last identity service update. Using current version of this service from "dev" branch gives the following error:
I forgot to create this pull request yesterday, sorry for that.
=> Students service update

MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada.docker.yml
=> (#82) adding the ntrada docker

MiniSpace.Services.Events/src/MiniSpace.Services.Events.Api/Program.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/CancelInterestInEvent.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/CancelSignUpToEvent.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/Handlers/AddEventHandler.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/Handlers/CancelInterestInEventHandler.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/Handlers/CancelSignUpToEventHandler.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/Handlers/UpdateEventHandler.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/UpdateEvent.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/DTO/EventDto.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Events/EventUpdated.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Events/StudentCancelledInterestInEvent.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Events/StudentCancelledSignUpToEvent.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Exceptions/EmptyRequiredEventFieldException.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Exceptions/InvalidEventCapacityException.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Exceptions/InvalidEventFeeException.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Exceptions/InvalidUpdatedEventCapacityException.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Exceptions/InvalidUpdatedEventFeeException.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Services/IEventValidator.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Core/Entities/Address.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Core/Entities/Event.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Core/Exceptions/StudentNotInterestedInEventException.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Core/Exceptions/StudentNotSignedUpException.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Infrastructure/Mongo/Documents/Extensions.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Infrastructure/Services/EventValidator.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Infrastructure/Services/Workers/EventStateUpdaterWorker.cs
- new endpoints for editing event, cancelling sign up and interest in event
- updated EventDto 
- updated background worker
- updated event validation
=> Events service update

.github/workflows/azure_synchronisation.yml, .github/workflows/build_microservices.yml, .github/workflows/cloud_deploy.yml
=> (#88) pipeline scripts udpate

MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Api/Program.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Api/Properties/launchSettings.json, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Entities/AggregateId.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/DomainException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/FriendAcceptanceException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/FriendDeclinationException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/FriendshipStateException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/InvalidAggregateIdException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/InvalidFriendInvitationException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/InvalidFriendRequestException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Core/Exceptions/InvalidFriendshipStateException.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Infrastructure/Exceptions/ExceptionToResponseMapper.cs, MiniSpace.Services.Friends/src/MiniSpace.Services.Friends.Infrastructure/Extensions.cs
adding the testing projects to the firnds service
=> (#97) (#82) testing project to the frined service

.github/workflows/azure_synchronisation.yml, .github/workflows/build_microservices.yml, .github/workflows/cloud_deploy.yml
Pipeline update to make it use the github server hosted runner.
=> (#88) pipieline-update to use the github hosted runner

MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/Handlers/AddEventHandler.cs
Fix bug regarding missing organization name in event entity
=> Events service - bug fix

MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada.docker.yml, MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada.yml, MiniSpace.Services.Posts/src/MiniSpace.Services.Posts.Api/Program.cs, MiniSpace.Services.Posts/src/MiniSpace.Services.Posts.Application/Queries/GetPost.cs, MiniSpace.Services.Posts/src/MiniSpace.Services.Posts.Infrastructure/Mongo/Queries/Handlers/GetPostHandler.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Events/EventsService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Events/IEventsService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Posts/IPostsService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Posts/PostsService.cs, MiniSpace.Web/src/MiniSpace.Web/DTO/PostDto.cs, MiniSpace.Web/src/MiniSpace.Web/HttpClients/CustomHttpClient.cs, MiniSpace.Web/src/MiniSpace.Web/HttpClients/IHttpClient.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Events/UpdateEventModel.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Posts/CreatePostModel.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Posts/UpdatePostModel.cs, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/ManageStudents.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/Event.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventAdd.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventUpdate.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventsOrganize.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Posts/Dialogs/DeletePostDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Posts/Post.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Posts/PostCreate.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Posts/PostUpdate.razor
@SaintAngeLs, unfortunately, I was not able to change workflow because of my token scopes not set to workflow. Updating the token could take too much time now, so if you want to have deployment on dev, you have to remember about changing these lines in cloud-deploy.yml.
=> Frontend issues resolving and adding some functionalities for posts

MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/AddEvent.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/Handlers/AddEventHandler.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Commands/SearchEvents.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Application/Services/Clients/IOrganizationsServiceClient.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Core/Repositories/IEventRepository.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Infrastructure/Mongo/Repositories/EventMongoRepository.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Infrastructure/Mongo/Repositories/Extensions.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Infrastructure/Services/Clients/OrganizationsServiceClient.cs, MiniSpace.Services.Events/src/MiniSpace.Services.Events.Infrastructure/Services/EventService.cs
This PR should handle all missing organizations functionality that was requested. Following changes will not compatible with current frontend, creating events and searching events won't work.
=> Events service update - organizations restructurization

MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada-async.docker.yml, MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada-async.yml, MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada.docker.yml, MiniSpace.APIGateway/src/MiniSpace.APIGateway/ntrada.yml, MiniSpace.Services.Comments/src/MiniSpace.Services.Comments.Api/Program.cs, MiniSpace.Services.Comments/src/MiniSpace.Services.Comments.Application/Queries/GetComment.cs, MiniSpace.Services.Comments/src/MiniSpace.Services.Comments.Infrastructure/Mongo/Queries/Handlers/GetCommentHandler.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Comments/CommentsService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Comments/ICommentsService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Reports/IReportsService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Reports/ReportsService.cs, MiniSpace.Web/src/MiniSpace.Web/DTO/Enums/ReportCategory.cs, MiniSpace.Web/src/MiniSpace.Web/DTO/States/ReportState.cs, MiniSpace.Web/src/MiniSpace.Web/DTO/Types/ReportContextType.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Reports/CreateReportModel.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Reports/GetStudentReportsModel.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Reports/SearchReportsModel.cs, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/ManageReportDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/SearchReportsDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/ManageReports.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Comments/CommentDetails.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Comments/CommentsTree.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/Event.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Friends/FriendsDetails.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Posts/Post.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Reports/Dialogs/CreateReportDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Reports/Dialogs/ReportDetailsDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Reports/ReportTargetSection.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Reports/StudentReports.razor, MiniSpace.Web/src/MiniSpace.Web/Shared/MainLayout.razor
This pull request provides the following features:
- options of reporting events, posts, comments and student profiles
- panel for student to show details of created reports and eventually cancel them
- panel for admin to search all reports by some criteria and manage them
Student and Admin can be forwarded to pages of reported elements by suitable buttons from report details dialog. Thanks to Local Storage, searching criteria and chosen report are reloaded after coming back.
=> Frontend reports

MiniSpace.Web/src/MiniSpace.Web/Areas/Organizations/IOrganizationsService.cs, MiniSpace.Web/src/MiniSpace.Web/Areas/Organizations/OrganizationsService.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Organizations/OrganizationModel.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Organizations/OrganizerModel.cs, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/AddOrganizationDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/DeleteOrganizationDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/ManageReportDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/ManageStudentDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/OrganizationDetailsDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/Dialogs/SearchReportsDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/ManageOrganizations.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/ManageStudents.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventCreate.razor
This pull request provides changes mentioned in #235.
=> Frontend admin update

MiniSpace.Services.Reports/src/MiniSpace.Services.Reports.Infrastructure/Mongo/Repositories/ReportMongoRepository.cs
=>  Fix bug with report creating

MiniSpace.Web/src/MiniSpace.Web/Components/RadzenLabelWithCheckbox.razor, MiniSpace.Web/src/MiniSpace.Web/Components/RadzenLabelWithDatePicker.razor, MiniSpace.Web/src/MiniSpace.Web/Components/RadzenLabelWithNumeric.razor, MiniSpace.Web/src/MiniSpace.Web/Components/RadzenLabelWithTextBoxes.razor, MiniSpace.Web/src/MiniSpace.Web/Components/RadzenLabels.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Account/CompleteRegistration.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Account/FirstSignIn.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Account/ShowAccount.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Account/SignIn.razor, MiniSpace.Web/src/MiniSpace.Web/Shared/MainLayout.razor
=> Fix bug with completing registration after first signing in

MiniSpace.Web/src/MiniSpace.Web/Components/RadzenPostCard.razor, MiniSpace.Web/src/MiniSpace.Web/DTO/StudentDto.cs, MiniSpace.Web/src/MiniSpace.Web/Models/Events/SearchEventsModel.cs, MiniSpace.Web/src/MiniSpace.Web/Pages/Account/ShowAccount.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/ManageOrganizations.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/ManageReports.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Admin/ManageStudents.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/Dialogs/EventsSearchDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/Dialogs/InviteFriendsToEventDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventCreate.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventUpdate.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventsOrganize.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Events/EventsSearch.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Friends/Dialogs/FriendsDialog.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Friends/Friends.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Friends/FriendsRequests.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Friends/FriendsSearch.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Friends/SentRequests.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Notifications/AllNotifications.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Notifications/HistoryNotifications.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Notifications/NewNotifications.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Posts/Post.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Posts/PostUpdate.razor, MiniSpace.Web/src/MiniSpace.Web/Pages/Reports/StudentReports.razor, MiniSpace.Web/src/MiniSpace.Web/Shared/MainLayout.razor
This pull request provides the following changes:
- fixing some small flaws which I've observed
- saving criteria of searching events and organizer events at LocalStorage
- adding progress bar circulars to pages for friends, notifications, reports and admin
=> Frontend updates

.github/workflows/cloud_deploy.yml, MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Infrastructure/Mongo/Documents/StudentNotificationsDocument.cs, MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Infrastructure/Mongo/Repositories/StudentNotificationsMongoRepository.cs, MiniSpace.Web/src/MiniSpace.Web/DTO/Notifications/NotificationLinkFactory.cs
=> (#266) hot fix notification service

LICENSE
=> (#273) Update the license file origin

.github/workflows/cloud_deploy.yml, .github/workflows/gitlab_sync.yml, .github/workflows/gitlab_sync_pr_issues.yml, .github/workflows/sync_prs_issues.py, .gitlab-ci.yml, MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Api/Program.cs, MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Application/Hubs/ChatHub.cs, MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Core/Entities/Message.cs, MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Core/Entities/MessageType.cs, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Api/MiniSpace.Services.Organizations.Api.sln, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Api/Program.cs, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Application/MiniSpace.Services.Organizations.Application.sln, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Core/Entities/Invitation.cs, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Core/Entities/Organization.cs, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Core/Entities/User.cs, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Core/Exceptions/UserAlreadyInvitedException.cs, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Core/Exceptions/UserAlreadySignedUpException.cs, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Core/MiniSpace.Services.Organizations.Core.sln, MiniSpace.Services.Organizations/src/MiniSpace.Services.Organizations.Infrastructure/MiniSpace.Services.Organizations.Infrastructure.sln, MiniSpace.Web/src/MiniSpace.Web/Pages/Feeds/UserInformation.razor, config.toml, deploy.sh
=> #305 add syncronisation with gitlab

.github/workflows/cloud_deploy.yml, .github/workflows/gitlab_sync.yml, .github/workflows/sync_prs_issues.py, .gitlab-ci.yml
=> #305 fix incorrect format gitlab ci

.github/workflows/cloud_deploy.yml, .gitlab-ci.yml, MiniSpace/compose/services-prod.yml, deploy.sh
=> #305 update build sh

.github/workflows/codeql.yml, .github/workflows/gitguardian.yml, .github/workflows/ossaranalyzer.yml, .github/workflows/securitycodescan.yml, .github/workflows/vulnerability_check.yml, MiniSpace.Services.Notifications/src/MiniSpace.Services.Notifications.Application/Hubs/NotificationHub.cs
Update secrets credentials issues vulnerabilities
=> #305 vulnerabilities issues update

.github/workflows/vulnerability_check.yml
Update github actions bot configuration
=> #305 update github actions bot configuration

.github/CODEOWNERS
Update github merge requests settings
=> #305 update github merge requests settings

MiniSpace.Services.Identity/tests/api-p-test.py
Organization service udpate, add the layouts for the organizations in blazor server
=> #342 Blazor application layout update

README.md
=> (#425) Update readme 
